
import { CollocationCategory } from '../types';

export const COLLOCATION_CATEGORIES: CollocationCategory[] = [
  {
    category: 'Verb + Noun',
    description: 'These collocations involve a common verb paired with a noun. Mastering these will help you sound more natural.',
    collocations: [
      { collocation: 'make a decision', example: 'I need to make a decision about my future.' },
      { collocation: 'take a risk', example: 'Starting a business always involves taking a risk.' },
      { collocation: 'do your homework', example: 'Please do your homework before you watch TV.' },
      { collocation: 'give advice', example: 'Could you give me some advice?' },
      { collocation: 'break a promise', example: 'It\'s important not to break a promise.' },
      { collocation: 'catch a cold', example: 'Wear a jacket, or you might catch a cold.' },
      { collocation: 'save time', example: 'Taking the highway will save us time.' },
      { collocation: 'make progress', example: 'The students are making progress in their English studies.' },
      { collocation: 'take a break', example: 'Let\'s take a break and get some coffee.' },
      { collocation: 'pay attention', example: 'Please pay attention to the instructions.' },
      { collocation: 'make an effort', example: 'You need to make an effort to improve your grades.' },
      { collocation: 'take notes', example: 'I always take notes during lectures.' },
      { collocation: 'lose weight', example: 'She wants to lose weight before the wedding.' },
      { collocation: 'gain experience', example: 'Internships help you gain experience in your field.' },
      { collocation: 'raise awareness', example: 'The campaign aims to raise awareness about climate change.' },
      { collocation: 'meet a deadline', example: 'We worked overtime to meet the deadline.' },
      { collocation: 'make a mistake', example: 'Everyone makes mistakes; it\'s how we learn.' },
      { collocation: 'run a business', example: 'She runs a successful business from home.' },
      { collocation: 'keep a secret', example: 'Can you keep a secret?' },
      { collocation: 'make an appointment', example: 'I need to make an appointment with the dentist.' },
    ],
  },
  {
    category: 'Adjective + Noun',
    description: 'These collocations consist of an adjective that is typically used to describe a particular noun.',
    collocations: [
      { collocation: 'heavy rain', example: 'We cancelled the picnic because of the heavy rain.' },
      { collocation: 'strong coffee', example: 'I need a strong coffee to wake up this morning.' },
      { collocation: 'deep sleep', example: 'He was in a deep sleep and didn\'t hear the alarm.' },
      { collocation: 'high-paying job', example: 'She is looking for a high-paying job in finance.' },
      { collocation: 'rich vocabulary', example: 'Reading books is a great way to build a rich vocabulary.' },
      { collocation: 'common knowledge', example: 'It is common knowledge that the Earth is round.' },
      { collocation: 'fast food', example: 'Eating too much fast food is unhealthy.' },
      { collocation: 'close friend', example: 'She shared the news with her close friends first.' },
      { collocation: 'hard work', example: 'Success requires hard work and dedication.' },
      { collocation: 'bright future', example: 'The young graduate has a bright future ahead.' },
      { collocation: 'broad daylight', example: 'The robbery occurred in broad daylight.' },
      { collocation: 'key factor', example: 'Education is a key factor in economic development.' },
      { collocation: 'golden opportunity', example: 'This scholarship is a golden opportunity for students.' },
      { collocation: 'fatal mistake', example: 'Ignoring safety protocols could be a fatal mistake.' },
      { collocation: 'heated debate', example: 'The proposal sparked a heated debate in parliament.' },
      { collocation: 'vicious cycle', example: 'Poverty often creates a vicious cycle that\'s hard to escape.' },
      { collocation: 'burning desire', example: 'He has a burning desire to become a doctor.' },
      { collocation: 'harsh criticism', example: 'The film received harsh criticism from reviewers.' },
    ],
  },
  {
    category: 'Adverb + Adjective',
    description: 'In these collocations, an adverb is used to intensify or modify an adjective.',
    collocations: [
      { collocation: 'deeply concerned', example: 'She was deeply concerned about her exam results.' },
      { collocation: 'bitterly disappointed', example: 'He was bitterly disappointed when he didn\'t get the job.' },
      { collocation: 'highly successful', example: 'Her new book was highly successful.' },
      { collocation: 'painfully shy', example: 'As a child, I was painfully shy.' },
      { collocation: 'fully aware', example: 'I am fully aware of the consequences.' },
      { collocation: 'utterly ridiculous', example: 'His excuse for being late was utterly ridiculous.' },
      { collocation: 'perfectly clear', example: 'Let me make this perfectly clear: we will not tolerate cheating.' },
      { collocation: 'seriously injured', example: 'Three people were seriously injured in the accident.' },
      { collocation: 'highly unlikely', example: 'It is highly unlikely that he will agree to that.' },
      { collocation: 'absolutely essential', example: 'A valid passport is absolutely essential for travel.' },
      { collocation: 'wildly popular', example: 'The new app became wildly popular overnight.' },
      { collocation: 'genuinely surprised', example: 'I was genuinely surprised by the announcement.' },
      { collocation: 'blissfully unaware', example: 'She was blissfully unaware of the danger.' },
      { collocation: 'mildly annoyed', example: 'He seemed mildly annoyed by the interruption.' },
      { collocation: 'fiercely competitive', example: 'The job market is fiercely competitive these days.' },
      { collocation: 'distinctly different', example: 'The two approaches are distinctly different.' },
    ],
  },
  {
    category: 'Verb + Adverb',
    description: 'These collocations pair verbs with adverbs that naturally modify them.',
    collocations: [
      { collocation: 'strongly recommend', example: 'I strongly recommend this restaurant.' },
      { collocation: 'firmly believe', example: 'I firmly believe in equal opportunities.' },
      { collocation: 'totally agree', example: 'I totally agree with your point of view.' },
      { collocation: 'flatly refuse', example: 'She flatly refused to answer any questions.' },
      { collocation: 'badly need', example: 'This house badly needs renovation.' },
      { collocation: 'deeply regret', example: 'We deeply regret any inconvenience caused.' },
      { collocation: 'hardly know', example: 'I hardly know her; we\'ve only met once.' },
      { collocation: 'sincerely apologize', example: 'I sincerely apologize for the delay.' },
      { collocation: 'eagerly await', example: 'Fans eagerly await the sequel.' },
      { collocation: 'bitterly complain', example: 'Customers bitterly complained about the service.' },
      { collocation: 'vaguely remember', example: 'I vaguely remember meeting him years ago.' },
      { collocation: 'categorically deny', example: 'The company categorically denied the allegations.' },
    ],
  },
  {
    category: 'Noun + Noun',
    description: 'These collocations combine two nouns that commonly appear together.',
    collocations: [
      { collocation: 'traffic jam', example: 'We got stuck in a traffic jam for two hours.' },
      { collocation: 'blood pressure', example: 'High blood pressure can lead to heart disease.' },
      { collocation: 'carbon footprint', example: 'We should all try to reduce our carbon footprint.' },
      { collocation: 'job satisfaction', example: 'Job satisfaction is more important than salary to some people.' },
      { collocation: 'brain drain', example: 'Many countries suffer from brain drain as talented people emigrate.' },
      { collocation: 'generation gap', example: 'The generation gap makes communication difficult.' },
      { collocation: 'rush hour', example: 'Avoid driving during rush hour if possible.' },
      { collocation: 'safety measures', example: 'The company implemented new safety measures.' },
      { collocation: 'side effects', example: 'This medication may cause side effects.' },
      { collocation: 'climate change', example: 'Climate change is the greatest challenge of our time.' },
      { collocation: 'human rights', example: 'Everyone deserves basic human rights.' },
      { collocation: 'role model', example: 'Parents should be role models for their children.' },
    ],
  },
  {
    category: 'Preposition Collocations',
    description: 'These collocations involve specific prepositions that follow certain words.',
    collocations: [
      { collocation: 'good at', example: 'She is very good at mathematics.' },
      { collocation: 'interested in', example: 'I\'m interested in learning about history.' },
      { collocation: 'afraid of', example: 'Many children are afraid of the dark.' },
      { collocation: 'responsible for', example: 'Who is responsible for this mess?' },
      { collocation: 'different from', example: 'British English is different from American English.' },
      { collocation: 'married to', example: 'She has been married to him for ten years.' },
      { collocation: 'famous for', example: 'Paris is famous for the Eiffel Tower.' },
      { collocation: 'worried about', example: 'I\'m worried about the upcoming exam.' },
      { collocation: 'capable of', example: 'She is capable of achieving great things.' },
      { collocation: 'proud of', example: 'I\'m so proud of my daughter\'s achievements.' },
      { collocation: 'similar to', example: 'Your idea is similar to what I was thinking.' },
      { collocation: 'based on', example: 'The movie is based on a true story.' },
    ],
  },
];
