
export const DID_YOU_KNOW_FACTS: string[] = [
  "The word 'goodbye' originally comes from an Old English phrase meaning 'God be with ye'.",
  "'I am' is the shortest complete sentence in the English language.",
  "A 'pangram' is a sentence that contains every letter of the alphabet. The most famous is: 'The quick brown fox jumps over the lazy dog.'",
  "The most common adjective used in English is 'good'.",
  "The word 'alphabet' comes from the first two letters of the Greek alphabet: alpha and beta.",
  "The dot over the letter 'i' and 'j' is called a 'tittle'.",
  "Shakespeare is credited with adding over 1,700 words to the English language, including 'eyeball', 'swagger', and 'lonely'.",
  "The word 'uncopyrightable' is the longest English word in normal use that contains no letter more than once.",
  "The oldest English word that is still in common use is 'town'.",
  "A 'crutch word' is a word or phrase that is used too often, such as 'like', 'actually', or 'honestly'.",
  "The word 'set' has more definitions than any other word in the English language.",
  "'Bookkeeper' is the only unhyphenated English word with three consecutive double letters.",
  "The word 'listen' contains the same letters as the word 'silent'.",
  "The past tense for the English verb 'dare' is 'durst', but it is rarely used today.",
  "The word 'nerd' was first coined by Dr. Seuss in his book 'If I Ran the Zoo'.",
  "The shortest complete sentence in English is 'Go!' - it has an implied subject 'you'.",
  "The word 'queue' is the only word in English that is pronounced the same way even if you remove the last four letters.",
  "The letter 'E' is the most commonly used letter in the English language.",
  "The word 'strength' is the longest English word with only one vowel.",
  "The word 'rhythm' is the longest English word without a traditional vowel.",
  "The symbol '&' is called an ampersand and was once considered the 27th letter of the alphabet.",
  "The English language has more words than any other language in the world - over 1 million words.",
  "The word 'typewriter' is the longest word that can be typed using only one row of keys on a QWERTY keyboard.",
  "The word 'almost' is the longest word in English with all letters in alphabetical order.",
  "The plural of 'mouse' (computer) is 'mouses' in technical English, not 'mice'.",
  "The word 'Pneumonoultramicroscopicsilicovolcanoconiosis' is the longest word in major dictionaries.",
  "The word 'OK' or 'Okay' is the most widely understood word in the world.",
  "English is the official language of the sky - all international pilots must speak English.",
  "The word 'girl' originally meant a young person of either gender in Old English.",
  "The sentence 'The quick brown fox jumps over the lazy dog' uses every letter of the alphabet.",
  "The word 'checkmate' in chess comes from the Persian phrase 'Shah Mat', meaning 'the king is dead'.",
  "The dot on top of lowercase 'i' and 'j' wasn't added until the Middle Ages.",
  "The word 'nice' originally meant 'silly' or 'foolish' in the 13th century.",
  "The longest one-syllable word in English is 'screeched'.",
  "The word 'cleave' is the only English word with two synonyms that are antonyms of each other: 'adhere' and 'separate'.",
  "The word 'month' has no perfect rhyme in English.",
  "The sentence 'Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo' is grammatically correct.",
  "The @ symbol is called 'at' in English but has different names in other languages, like 'snail' in Italian.",
  "The words 'month', 'orange', 'silver', and 'purple' have no perfect rhymes.",
  "The word 'swims' reads the same upside down.",
  "The phrase 'long time no see' is believed to be a literal translation from Chinese.",
  "The word 'mortgage' literally means 'death pledge' in French.",
  "The word 'salary' comes from the Latin word for salt, as Roman soldiers were sometimes paid in salt.",
  "The letter 'Q' is the least frequently used letter in English.",
  "The word 'strengths' has only one vowel but nine letters.",
  "The expression 'mind your Ps and Qs' may come from printers having to be careful with lowercase 'p' and 'q' types.",
  "The word 'clue' originally meant a ball of thread, from the Greek myth of Theseus and the Minotaur.",
  "The word 'terrible' once meant 'causing terror' but now just means 'very bad'.",
  "The word 'quarantine' comes from Italian 'quaranta giorni', meaning 40 days - the time ships had to wait before docking."
];

