// AUTO-GENERATED by scripts/extract-meta.cjs — do not edit by hand.
// Re-run that script after editing grammarTopics.tsx.
export interface GrammarTopicMeta {
  id: string;
  title: string;
  category: string;
}

export const GRAMMAR_TOPICS_META: GrammarTopicMeta[] = [
  {
    "id": "present-simple",
    "title": "Present Simple Tense",
    "category": "Present & Past Tenses"
  },
  {
    "id": "present-progressive",
    "title": "Present Progressive Tense",
    "category": "Present & Past Tenses"
  },
  {
    "id": "past-simple",
    "title": "Past Simple Tense",
    "category": "Present & Past Tenses"
  },
  {
    "id": "past-progressive",
    "title": "Past Progressive Tense",
    "category": "Present & Past Tenses"
  },
  {
    "id": "present-perfect",
    "title": "Present Perfect Tense",
    "category": "Present & Past Tenses"
  },
  {
    "id": "present-perfect-progressive",
    "title": "Present Perfect Progressive",
    "category": "Present & Past Tenses"
  },
  {
    "id": "past-perfect",
    "title": "Past Perfect Tense",
    "category": "Present & Past Tenses"
  },
  {
    "id": "past-perfect-progressive",
    "title": "Past Perfect Progressive",
    "category": "Present & Past Tenses"
  },
  {
    "id": "future-simple",
    "title": "Future Simple Tense",
    "category": "Future Tenses"
  },
  {
    "id": "future-progressive",
    "title": "Future Progressive Tense",
    "category": "Future Tenses"
  },
  {
    "id": "future-perfect",
    "title": "Future Perfect Tense",
    "category": "Future Tenses"
  },
  {
    "id": "future-perfect-progressive",
    "title": "Future Perfect Progressive",
    "category": "Future Tenses"
  },
  {
    "id": "articles",
    "title": "Articles: A, An, The",
    "category": "Nouns & Determiners"
  },
  {
    "id": "countable-uncountable-nouns",
    "title": "Countable & Uncountable Nouns",
    "category": "Nouns & Determiners"
  },
  {
    "id": "pronouns",
    "title": "Pronouns",
    "category": "Nouns & Determiners"
  },
  {
    "id": "adjectives-adverbs",
    "title": "Adjectives & Adverbs",
    "category": "Adjectives & Adverbs"
  },
  {
    "id": "comparative-superlative",
    "title": "Comparatives & Superlatives",
    "category": "Adjectives & Adverbs"
  },
  {
    "id": "modal-verbs",
    "title": "Modal Verbs",
    "category": "Verbs"
  },
  {
    "id": "gerunds-infinitives",
    "title": "Gerunds & Infinitives",
    "category": "Verbs"
  },
  {
    "id": "prepositions",
    "title": "Prepositions",
    "category": "Prepositions & Conjunctions"
  },
  {
    "id": "conjunctions",
    "title": "Conjunctions",
    "category": "Prepositions & Conjunctions"
  },
  {
    "id": "passive-voice",
    "title": "Passive Voice",
    "category": "Sentence Structure"
  },
  {
    "id": "subject-verb-agreement",
    "title": "Subject-Verb Agreement",
    "category": "Sentence Structure"
  },
  {
    "id": "question-formation",
    "title": "Question Formation",
    "category": "Sentence Structure"
  },
  {
    "id": "reported-speech",
    "title": "Reported Speech",
    "category": "Sentence Structure"
  },
  {
    "id": "direct-and-indirect-speech",
    "title": "Direct & Indirect Speech",
    "category": "Sentence Structure"
  },
  {
    "id": "sentence-fragments",
    "title": "Sentence Fragments",
    "category": "Sentence Structure"
  },
  {
    "id": "simple-and-complex-sentences",
    "title": "Simple & Complex Sentences",
    "category": "Sentence Structure"
  },
  {
    "id": "conditionals",
    "title": "Conditionals (If Clauses)",
    "category": "Clauses"
  },
  {
    "id": "relative-clauses",
    "title": "Relative Clauses",
    "category": "Clauses"
  },
  {
    "id": "commas",
    "title": "Commas",
    "category": "Punctuation"
  },
  {
    "id": "apostrophes",
    "title": "Apostrophes",
    "category": "Punctuation"
  },
  {
    "id": "semicolons-colons",
    "title": "Semicolons & Colons",
    "category": "Punctuation"
  },
  {
    "id": "quotation-marks",
    "title": "Quotation Marks",
    "category": "Punctuation"
  },
  {
    "id": "hyphens",
    "title": "Hyphens & Compound Words",
    "category": "Punctuation"
  },
  {
    "id": "subjunctive-mood",
    "title": "Subjunctive Mood",
    "category": "Advanced Grammar"
  },
  {
    "id": "cleft-sentences",
    "title": "Cleft Sentences",
    "category": "Advanced Grammar"
  },
  {
    "id": "inversion",
    "title": "Inversion",
    "category": "Advanced Grammar"
  },
  {
    "id": "ellipsis",
    "title": "Ellipsis",
    "category": "Advanced Grammar"
  },
  {
    "id": "used-to-vs-would",
    "title": "Used To vs Would",
    "category": "Common Confusions"
  },
  {
    "id": "wish-vs-hope",
    "title": "Wish vs Hope",
    "category": "Common Confusions"
  }
];
