
import { IdiomCategory } from '../types';

export const IDIOMS_CATEGORIES: IdiomCategory[] = [
  {
    category: 'General Usage',
    idioms: [
      { idiom: 'A dime a dozen', meaning: 'Very common and of little value.', example: 'Experts in this field are a dime a dozen.' },
      { idiom: 'Add insult to injury', meaning: 'To worsen an unfavorable situation.', example: 'To add insult to injury, after cancelling my flight, the airline refused to refund my ticket.' },
      { idiom: 'Beat around the bush', meaning: 'Avoid saying what you mean, usually because it is uncomfortable.', example: 'Stop beating around the bush and just tell me what happened.' },
      { idiom: 'Better late than never', meaning: 'Better to arrive or do something late than not at all.', example: 'He finally paid me the money he owed me. Well, better late than never.' },
      { idiom: 'Bite the bullet', meaning: 'To endure a difficult or unpleasant situation with courage.', example: 'I had to bite the bullet and finish the project even though I was tired.' },
      { idiom: 'Break the ice', meaning: 'To initiate social conversation or interaction.', example: 'He told a joke to break the ice at the start of the meeting.' },
      { idiom: 'Cost an arm and a leg', meaning: 'To be extremely expensive.', example: 'That new car must have cost him an arm and a leg.' },
      { idiom: 'Cut somebody some slack', meaning: 'Don\'t be so critical; be more forgiving.', example: 'He\'s having a tough week, so cut him some slack.' },
      { idiom: 'Don\'t judge a book by its cover', meaning: 'Don\'t judge something primarily on its appearance.', example: 'He may look a bit strange, but don\'t judge a book by its cover.' },
      { idiom: 'Get out of hand', meaning: 'To become uncontrollable.', example: 'The party got out of hand, and the police were called.' },
      { idiom: 'Get your act together', meaning: 'Behave properly or work more effectively.', example: 'You need to get your act together if you want to pass this class.' },
      { idiom: 'Go down in flames', meaning: 'To fail spectacularly.', example: 'His ambitious project went down in flames when he lost all funding.' },
      { idiom: 'Hang in there', meaning: 'Don\'t give up; persevere.', example: 'I know you\'re tired, but hang in there, you\'re almost finished.' },
      { idiom: 'Hit the nail on the head', meaning: 'To describe exactly what is causing a situation or problem.', example: 'You hit the nail on the head when you said our main issue is communication.' },
      { idiom: 'Jump on the bandwagon', meaning: 'Join a popular trend or activity.', example: 'So many people are buying that new phone; I might as well jump on the bandwagon.' },
      { idiom: 'Make a long story short', meaning: 'To tell something briefly.', example: 'To make a long story short, we missed our flight.' },
      { idiom: 'Miss the boat', meaning: 'To lose an opportunity.', example: 'The application was due yesterday; I think I missed the boat.' },
      { idiom: 'On the ball', meaning: 'To be quick to understand and react to things.', example: 'Our new project manager is really on the ball.' },
      { idiom: 'Pull yourself together', meaning: 'Calm down.', example: 'I know you\'re upset, but you need to pull yourself together and focus.' },
      { idiom: 'See eye to eye', meaning: 'To agree on a subject.', example: 'My boss and I don\'t always see eye to eye on marketing strategy.' },
      { idiom: 'So far so good', meaning: 'Progress has been satisfactory up to now.', example: 'How\'s the new project going? So far so good.' },
      { idiom: 'Speak of the devil', meaning: 'When the person you have just been talking about arrives.', example: 'Well, speak of the devil! We were just talking about you, Mark.' },
      { idiom: 'That\'s the last straw', meaning: 'The final tolerable act in a series of provocations.', example: 'He was late again, and that was the last straw. I fired him.' },
      { idiom: 'The best of both worlds', meaning: 'Enjoying two different opportunities at the same time.', example: 'Working from home is the best of both worlds; I have more family time and a great career.' },
      { idiom: 'Through thick and thin', meaning: 'Under all circumstances, no matter how difficult.', example: 'She has always supported me through thick and thin.' },
      { idiom: 'Your guess is as good as mine', meaning: 'I don\'t know either.', example: 'What time will he arrive? Your guess is as good as mine.' },
    ],
  },
  {
    category: 'Animals',
    idioms: [
      { idiom: 'A bull in a china shop', meaning: 'A clumsy person in a delicate situation.', example: 'He was like a bull in a china shop during the delicate negotiations.' },
      { idiom: 'A little bird told me', meaning: 'To have heard something from a secret source.', example: 'A little bird told me it\'s your birthday tomorrow.' },
      { idiom: 'Ants in your pants', meaning: 'To be unable to sit still.', example: 'The kids have ants in their pants today; they can\'t wait for the party.' },
      { idiom: 'Cat got your tongue?', meaning: 'A question asked when someone is unusually quiet.', example: 'You\'ve been silent all evening. Cat got your tongue?' },
      { idiom: 'Cry wolf', meaning: 'To raise a false alarm, with the result that a real alarm is ignored.', example: 'He has cried wolf so many times that no one believes him when he\'s actually in trouble.' },
      { idiom: 'Curiosity killed the cat', meaning: 'Being too inquisitive can lead to trouble.', example: 'I know you want to know what\'s in the box, but remember, curiosity killed the cat.' },
      { idiom: 'Fish out of water', meaning: 'To be in an unfamiliar and uncomfortable situation.', example: 'As a country boy, he felt like a fish out of water in the big city.' },
      { idiom: 'Go on a wild goose chase', meaning: 'To do something pointless or futile.', example: 'I went on a wild goose chase trying to find that rare book.' },
      { idiom: 'Hold your horses', meaning: 'To wait a moment; to not be so impatient.', example: 'Hold your horses! We\'re not ready to leave yet.' },
      { idiom: 'Kill two birds with one stone', meaning: 'To achieve two aims at once.', example: 'I can kill two birds with one stone by listening to an English podcast while I exercise.' },
      { idiom: 'Let sleeping dogs lie', meaning: 'To avoid restarting a conflict.', example: 'I wanted to ask him about the argument, but I decided to let sleeping dogs lie.' },
      { idiom: 'Let the cat out of the bag', meaning: 'To accidentally reveal a secret.', example: 'He let the cat out of the bag about the surprise party.' },
      { idiom: 'The elephant in the room', meaning: 'A major problem or controversial issue that is obviously present but avoided as a subject for discussion.', example: 'His gambling problem was the elephant in the room at the family dinner.' },
      { idiom: 'The lion\'s share', meaning: 'The largest portion of something.', example: 'As the lead investor, he took the lion\'s share of the profits.' },
      { idiom: 'When pigs fly', meaning: 'Something that will never happen.', example: 'He\'ll clean his room when pigs fly.' },
    ],
  },
  {
    category: 'Body Parts',
    idioms: [
      { idiom: 'All ears', meaning: 'Fully listening; attentive.', example: 'Tell me about your trip, I\'m all ears.' },
      { idiom: 'Bite your tongue', meaning: 'To stop yourself from saying something you want to say.', example: 'I had to bite my tongue to keep from criticizing his plan.' },
      { idiom: 'Break a leg', meaning: 'Good luck! (often said to actors before a performance).', example: 'You have a big performance tonight? Break a leg!' },
      { idiom: 'By the skin of your teeth', meaning: 'Just barely succeeding.', example: 'He passed the exam by the skin of his teeth.' },
      { idiom: '(Have a) foot in the door', meaning: 'A first step toward getting or doing something.', example: 'This internship could be my foot in the door at a great company.' },
      { idiom: 'Get cold feet', meaning: 'To become nervous about a big event and reconsider it.', example: 'The groom got cold feet the day before the wedding.' },
      { idiom: 'Get something off your chest', meaning: 'To talk about something that has been bothering you.', example: 'He felt much better after getting the problem off his chest.' },
      { idiom: 'Give someone the cold shoulder', meaning: 'To ignore someone deliberately.', example: 'After our argument, she gave me the cold shoulder for a week.' },
      { idiom: 'Have a change of heart', meaning: 'To change your opinion or the way you feel about something.', example: 'I was going to sell my car, but I had a change of heart.' },
      { idiom: 'Head over heels', meaning: 'Deeply in love.', example: 'They are head over heels for each other.' },
      { idiom: 'Keep an eye on', meaning: 'To watch or take care of something or someone.', example: 'Can you keep an eye on my bag for a minute?' },
      { idiom: 'Play it by ear', meaning: 'To decide how to deal with a situation as it develops.', example: 'We don\'t have a set schedule, we\'ll just play it by ear.' },
      { idiom: 'Pull someone\'s leg', meaning: 'To joke with someone; to tease them.', example: 'Don\'t worry, I\'m just pulling your leg. I didn\'t actually break your camera.' },
      { idiom: 'Rule of thumb', meaning: 'A broadly accurate guide or principle, based on practice rather than theory.', example: 'As a rule of thumb, you should add the pasta to boiling water.' },
    ],
  },
  {
    category: 'Feelings & Emotions',
    idioms: [
      { idiom: 'A blessing in disguise', meaning: 'A good thing that seemed bad at first.', example: 'Losing that job was a blessing in disguise; I found a much better one.' },
      { idiom: '(Have a) chip on your shoulder', meaning: 'To seem angry all the time because you think you have been treated unfairly.', example: 'He has a chip on his shoulder about not going to college.' },
      { idiom: 'Down in the dumps', meaning: 'Sad or depressed.', example: 'She\'s been down in the dumps ever since she lost her job.' },
      { idiom: 'Face the music', meaning: 'To accept responsibility for something you have done.', example: 'After crashing his dad\'s car, he had to go home and face the music.' },
      { idiom: 'Have mixed feelings', meaning: 'To be unsure how you feel about something.', example: 'I have mixed feelings about moving to a new city.' },
      { idiom: 'Head in the clouds', meaning: 'To be daydreaming and not paying attention.', example: 'He has his head in the clouds if he thinks he can pass the exam without studying.' },
      { idiom: 'Jump for joy', meaning: 'To be extremely happy.', example: 'She jumped for joy when she heard the good news.' },
      { idiom: 'On cloud nine', meaning: 'To be extremely happy and joyful.', example: 'She has been on cloud nine since she got engaged.' },
      { idiom: 'Saved by the bell', meaning: 'Rescued from a difficult situation at the very last moment.', example: 'I was about to give a wrong answer, but the fire alarm rang. I was saved by the bell!' },
      { idiom: 'Under the weather', meaning: 'To feel ill or sick.', example: 'I\'m feeling a bit under the weather today, so I\'m staying home.' },
    ],
  },
  {
    category: 'Food',
    idioms: [
      { idiom: 'A tough cookie', meaning: 'A very determined and resilient person.', example: 'She went through a lot, but she\'s a tough cookie.' },
      { idiom: '(The) apple of my eye', meaning: 'A person that is adored by someone.', example: 'His youngest daughter is the apple of his eye.' },
      { idiom: 'As cool as a cucumber', meaning: 'To be very calm, especially under pressure.', example: 'She was as cool as a cucumber during her job interview.' },
      { idiom: 'Bite off more than you can chew', meaning: 'To take on a task that is too big to handle.', example: 'By accepting two part-time jobs, he is biting off more than he can chew.' },
      { idiom: 'Cry over spilt milk', meaning: 'To be upset about something that has already happened and cannot be changed.', example: 'The report is already submitted; there\'s no use crying over spilt milk.' },
      { idiom: '(Don\'t) put all your eggs in one basket', meaning: 'Don\'t risk everything on the success of one venture.', example: 'It\'s wise to diversify your investments and not put all your eggs in one basket.' },
      { idiom: 'Go bananas', meaning: 'To become extremely angry, excited, or silly.', example: 'The crowd went bananas when the band came on stage.' },
      { idiom: 'In a nutshell', meaning: 'In a few words; concisely.', example: 'In a nutshell, the plan failed.' },
      { idiom: 'Piece of cake', meaning: 'Something that is very easy to do.', example: 'The exam was a piece of cake.' },
      { idiom: 'Sell like hotcakes', meaning: 'To sell very quickly and in large quantities.', example: 'The new phone is selling like hotcakes.' },
      { idiom: 'Spill the beans', meaning: 'To disclose a secret.', example: 'Come on, spill the beans! What did he say?' },
      { idiom: 'Take with a grain of salt', meaning: 'To not take something too seriously or literally.', example: 'You should take his promises with a grain of salt.' },
      { idiom: 'The cream of the crop', meaning: 'The best of a particular group.', example: 'The company only hires the cream of the crop from the top universities.' },
    ],
  },
  {
    category: 'Money',
    idioms: [
      { idiom: 'A penny for your thoughts', meaning: 'A way of asking what someone is thinking.', example: 'You seem quiet. A penny for your thoughts?' },
      { idiom: 'Break the bank', meaning: 'To be very expensive.', example: 'Eating at that restaurant will break the bank.' },
      { idiom: 'Cash cow', meaning: 'A business or product that generates a steady return of profits.', example: 'Their original software is a real cash cow for the company.' },
      { idiom: 'Go Dutch', meaning: 'To share the cost of something, especially a meal.', example: 'We decided to go Dutch on the dinner, so everyone paid for their own food.' },
      { idiom: 'Golden handshake', meaning: 'A large payment made to someone when they leave their job, either on retirement or when forced out.', example: 'The CEO received a generous golden handshake when he left the company.' },
      { idiom: 'Money doesn\'t grow on trees', meaning: 'Money is a limited resource and should be used carefully.', example: 'My son wants a new bike, but I told him that money doesn\'t grow on trees.' },
      { idiom: 'Money talks', meaning: 'People with money have more power and influence.', example: 'He got the best table in the restaurant. It\'s true that money talks.' },
      { idiom: 'Put your money where your mouth is', meaning: 'To take action to support what you are saying.', example: 'If you think the company will succeed, you should invest. Put your money where your mouth is.' },
    ]
  },
  {
    category: 'Time',
    idioms: [
      { idiom: 'Against the clock', meaning: 'To be rushed and have very little time to do something.', example: 'We were working against the clock to finish the report by the deadline.' },
      { idiom: 'At the eleventh hour', meaning: 'At the last possible moment.', example: 'They reached an agreement at the eleventh hour.' },
      { idiom: 'Beat the clock', meaning: 'To finish something just before the deadline.', example: 'She managed to beat the clock and submit her application just in time.' },
      { idiom: 'Call it a night', meaning: 'To stop an activity for the rest of the night.', example: 'It\'s getting late. I think I\'m going to call it a night.' },
      { idiom: 'In the nick of time', meaning: 'At the last possible moment.', example: 'The ambulance arrived in the nick of time to save him.' },
      { idiom: 'Kill time', meaning: 'To do something to occupy yourself while waiting for something to happen.', example: 'We have an hour before our flight, so let\'s go to the cafe to kill time.' },
      { idiom: 'Once in a blue moon', meaning: 'To happen very rarely.', example: 'I only see my old school friends once in a blue moon.' },
      { idiom: 'Turn back the hands of time', meaning: 'To go back to the past.', example: 'If I could turn back the hands of time, I would do things differently.' },
    ],
  },
  {
    category: 'Weather',
    idioms: [
      { idiom: 'A storm in a teacup', meaning: 'A lot of unnecessary anger and worry about a matter that is not important.', example: 'Their argument was just a storm in a teacup; they\'re friends again now.' },
      { idiom: 'Come rain or shine', meaning: 'No matter what happens.', example: 'I\'ll be at your game tomorrow, come rain or shine.' },
      { idiom: 'Every cloud has a silver lining', meaning: 'Every difficult or sad situation has a comforting or more hopeful aspect.', example: 'I was sad to leave my old job, but the new one is much better. Every cloud has a silver lining.' },
      { idiom: 'Get wind of something', meaning: 'To hear a rumor about something.', example: 'The reporter got wind of the scandal and published a story.' },
      { idiom: 'It never rains but it pours', meaning: 'When troubles come, they come all at once.', example: 'First I lost my keys, then my car broke down. It never rains but it pours.' },
      { idiom: 'On thin ice', meaning: 'In a precarious or risky situation.', example: 'After being late for the third time, he was on thin ice with his boss.' },
      { idiom: 'Rain on someone\'s parade', meaning: 'To spoil someone\'s pleasure or plans.', example: 'I don\'t want to rain on your parade, but the concert might be cancelled.' },
      { idiom: 'Steal someone\'s thunder', meaning: 'To take attention or credit away from someone else\'s achievements.', example: 'I was about to announce my engagement, but my sister stole my thunder by announcing her pregnancy.' },
    ]
  },
  {
    category: 'Work & Business',
    idioms: [
      { idiom: 'A learning curve', meaning: 'The rate of a person\'s progress in gaining experience or new skills.', example: 'There\'s a steep learning curve with this new software.' },
      { idiom: 'Back to the drawing board', meaning: 'When an attempt fails and it\'s time to start all over.', example: 'Our proposal was rejected, so it\'s back to the drawing board.' },
      { idiom: 'By the book', meaning: 'Strictly according to the rules.', example: 'Our accountant does everything by the book.' },
      { idiom: 'Call it a day', meaning: 'To stop working for the day.', example: 'We\'ve done enough for today, let\'s call it a day.' },
      { idiom: 'Cut corners', meaning: 'To do something in the easiest, cheapest, or fastest way, often sacrificing quality.', example: 'The company went out of business because they were cutting corners on safety.' },
      { idiom: 'Cut to the chase', meaning: 'Get to the point without wasting time.', example: 'I don\'t have much time, so please cut to the chase.' },
      { idiom: 'Go the extra mile', meaning: 'To make a special effort to achieve something.', example: 'She always goes the extra mile to help her clients.' },
      { idiom: 'Hit the ground running', meaning: 'To start something and proceed at a fast pace with great enthusiasm.', example: 'The new employee hit the ground running and was productive from her first day.' },
      { idiom: 'Learn the ropes', meaning: 'To learn the basics of a job or task.', example: 'It took me a few weeks to learn the ropes at my new job.' },
      { idiom: 'On the same page', meaning: 'To be in agreement about something.', example: 'Before we present to the client, let\'s make sure we are all on the same page.' },
      { idiom: 'Raise the bar', meaning: 'To set a higher standard.', example: 'Her performance really raised the bar for the rest of the team.' },
      { idiom: 'Think outside the box', meaning: 'To think in a creative and unconventional way.', example: 'We need to think outside the box to solve this problem.' },
    ],
  },
  {
    category: 'Colors',
    idioms: [
      { idiom: 'See red', meaning: 'To become very angry.', example: 'When he heard the news, he saw red and started shouting.' },
      { idiom: 'Out of the blue', meaning: 'Unexpectedly; without warning.', example: 'She called me out of the blue after five years.' },
      { idiom: 'Green with envy', meaning: 'To be very jealous.', example: 'She was green with envy when she saw her friend\'s new car.' },
      { idiom: 'White lie', meaning: 'A harmless or small lie, especially one told to avoid hurting someone.', example: 'I told a white lie and said I liked her new haircut.' },
      { idiom: 'In the red', meaning: 'To be in debt; losing money.', example: 'The company has been in the red for the past two years.' },
      { idiom: 'Golden opportunity', meaning: 'A very good chance to do something.', example: 'This internship is a golden opportunity to learn from experts.' },
      { idiom: 'Black sheep', meaning: 'A person who is different from the rest of their group and is often disapproved of.', example: 'He\'s the black sheep of the family; he never follows the rules.' },
      { idiom: 'Gray area', meaning: 'A situation where the rules are not clear.', example: 'The law on this matter is a gray area.' },
      { idiom: 'In the black', meaning: 'To be profitable; making money.', example: 'After years of losses, the business is finally in the black.' },
      { idiom: 'Once in a blue moon', meaning: 'Very rarely.', example: 'I only eat fast food once in a blue moon.' },
      { idiom: 'Roll out the red carpet', meaning: 'To give someone a special welcome.', example: 'They really rolled out the red carpet for the visiting dignitaries.' },
      { idiom: 'Tickled pink', meaning: 'To be very pleased or amused.', example: 'She was tickled pink when she won the award.' },
    ],
  },
  {
    category: 'Numbers',
    idioms: [
      { idiom: 'At sixes and sevens', meaning: 'In a state of confusion or disarray.', example: 'After the manager left, the office was at sixes and sevens.' },
      { idiom: 'Back to square one', meaning: 'To go back to the beginning; to start over.', example: 'The proposal was rejected, so we\'re back to square one.' },
      { idiom: 'Two\'s company, three\'s a crowd', meaning: 'A third person can make two people feel uncomfortable.', example: 'I didn\'t want to go to dinner with them; two\'s company, three\'s a crowd.' },
      { idiom: 'Dressed to the nines', meaning: 'Dressed very elegantly or formally.', example: 'Everyone was dressed to the nines at the gala.' },
      { idiom: 'A stitch in time saves nine', meaning: 'Fixing a problem early prevents it from getting worse.', example: 'Get that small leak fixed now; a stitch in time saves nine.' },
      { idiom: 'Six of one, half a dozen of the other', meaning: 'Two alternatives are equivalent or indifferent.', example: 'Whether we go by bus or train, it\'s six of one, half a dozen of the other.' },
      { idiom: 'On cloud nine', meaning: 'Extremely happy.', example: 'She\'s been on cloud nine since she got the promotion.' },
      { idiom: 'The whole nine yards', meaning: 'Everything; all of it.', example: 'We\'re planning the wedding with flowers, music, catering—the whole nine yards.' },
      { idiom: 'First things first', meaning: 'The most important things should be done before anything else.', example: 'We need to finish the report. First things first.' },
      { idiom: 'Ten a penny', meaning: 'Very common and therefore not valuable.', example: 'Smartphones are ten a penny these days.' },
    ],
  },
  {
    category: 'Travel & Transportation',
    idioms: [
      { idiom: 'In the driver\'s seat', meaning: 'In control of a situation.', example: 'After the promotion, she\'s really in the driver\'s seat.' },
      { idiom: 'Off the beaten path', meaning: 'In an unusual or remote place.', example: 'We found a wonderful restaurant off the beaten path.' },
      { idiom: 'Up in the air', meaning: 'Uncertain; not yet decided.', example: 'Our vacation plans are still up in the air.' },
      { idiom: 'All aboard', meaning: 'Everyone get on; time to leave.', example: 'All aboard! The train is about to depart.' },
      { idiom: 'Smooth sailing', meaning: 'Easy progress without difficulties.', example: 'Once we fixed the initial bugs, it was smooth sailing.' },
      { idiom: 'On the right track', meaning: 'Doing something correctly or well.', example: 'Your project proposal is on the right track.' },
      { idiom: 'Jump ship', meaning: 'To leave an organization or project suddenly.', example: 'Several employees jumped ship when the company started having financial problems.' },
      { idiom: 'Plain sailing', meaning: 'Easy and straightforward.', example: 'After we solved the main problem, the rest was plain sailing.' },
      { idiom: 'Take a back seat', meaning: 'To take a less important role.', example: 'He decided to take a back seat and let the younger team members lead.' },
      { idiom: 'Drive someone up the wall', meaning: 'To make someone very annoyed or angry.', example: 'His constant whistling is driving me up the wall.' },
      { idiom: 'Run out of steam', meaning: 'To lose energy or enthusiasm.', example: 'I was working hard, but I ran out of steam by 3 PM.' },
      { idiom: 'Full steam ahead', meaning: 'To proceed with maximum speed and energy.', example: 'Now that we have funding, it\'s full steam ahead on the project.' },
    ],
  },
  {
    category: 'Sports & Games',
    idioms: [
      { idiom: 'Drop the ball', meaning: 'To make a mistake; to fail to do something important.', example: 'I really dropped the ball by forgetting the meeting.' },
      { idiom: 'Move the goalposts', meaning: 'To change the rules or requirements unfairly.', example: 'Every time I meet their standards, they move the goalposts.' },
      { idiom: 'Play hardball', meaning: 'To be aggressive and uncompromising.', example: 'The negotiations got tough when they started playing hardball.' },
      { idiom: 'Throw in the towel', meaning: 'To give up; to quit.', example: 'After months of trying, he finally threw in the towel.' },
      { idiom: 'Ballpark figure', meaning: 'An approximate number.', example: 'I need a ballpark figure for the cost of the project.' },
      { idiom: 'Level playing field', meaning: 'A situation where everyone has an equal chance.', example: 'The new rules create a level playing field for all competitors.' },
      { idiom: 'Par for the course', meaning: 'What is normal or expected in a given situation.', example: 'Traffic jams are par for the course in this city.' },
      { idiom: 'Step up to the plate', meaning: 'To take action when needed; to take responsibility.', example: 'When the manager quit, she stepped up to the plate and took charge.' },
      { idiom: 'Hit it out of the park', meaning: 'To do something extremely well.', example: 'Her presentation really hit it out of the park.' },
      { idiom: 'Keep your eye on the ball', meaning: 'To stay focused on what\'s important.', example: 'Don\'t get distracted; keep your eye on the ball.' },
      { idiom: 'Game plan', meaning: 'A strategy for achieving a goal.', example: 'What\'s our game plan for the launch?' },
      { idiom: 'In someone\'s corner', meaning: 'Supporting someone.', example: 'Don\'t worry, I\'m in your corner on this decision.' },
      { idiom: 'The ball is in your court', meaning: 'It\'s your turn to make a decision or take action.', example: 'I\'ve made my offer; the ball is in your court now.' },
      { idiom: 'Ahead of the game', meaning: 'In an advantageous position; ahead of the competition.', example: 'By starting early, we\'re ahead of the game.' },
    ],
  },
  {
    category: 'Home & Family',
    idioms: [
      { idiom: 'Bring home the bacon', meaning: 'To earn money to support your family.', example: 'My father works two jobs to bring home the bacon.' },
      { idiom: 'Like father, like son', meaning: 'A son tends to be similar to his father.', example: 'He\'s a doctor just like his dad. Like father, like son.' },
      { idiom: 'Blood is thicker than water', meaning: 'Family relationships are stronger than other relationships.', example: 'Even though we argue, we always support each other. Blood is thicker than water.' },
      { idiom: 'Home sweet home', meaning: 'A feeling of comfort and happiness when you arrive home.', example: 'After a long trip, it\'s great to be back. Home sweet home!' },
      { idiom: 'Keep it in the family', meaning: 'To keep something private within the family.', example: 'Let\'s keep this issue in the family and not discuss it with outsiders.' },
      { idiom: 'A chip off the old block', meaning: 'Someone who is very similar to their parent.', example: 'She\'s a great artist, just like her mother. A chip off the old block.' },
      { idiom: 'Close to home', meaning: 'Affecting you personally or emotionally.', example: 'That criticism hit close to home.' },
      { idiom: 'Make yourself at home', meaning: 'To make yourself comfortable in someone else\'s house.', example: 'Please sit down and make yourself at home.' },
      { idiom: 'A home away from home', meaning: 'A place where you feel comfortable and welcome.', example: 'This coffee shop has become my home away from home.' },
      { idiom: 'Wear the pants', meaning: 'To be the person in charge in a relationship or family.', example: 'In their household, she wears the pants.' },
      { idiom: 'Born with a silver spoon in one\'s mouth', meaning: 'Born into a wealthy family.', example: 'He never had to work hard; he was born with a silver spoon in his mouth.' },
    ],
  },
  {
    category: 'Clothing & Fashion',
    idioms: [
      { idiom: 'Dress to impress', meaning: 'To wear nice clothes to make a good impression.', example: 'It\'s an important meeting, so make sure you dress to impress.' },
      { idiom: 'Caught with your pants down', meaning: 'To be caught unprepared or in an embarrassing situation.', example: 'The surprise inspection caught us with our pants down.' },
      { idiom: 'Old hat', meaning: 'Something that is familiar or outdated.', example: 'This technology is old hat now; everyone uses the new version.' },
      { idiom: 'Roll up your sleeves', meaning: 'To prepare for hard work.', example: 'We have a lot to do, so let\'s roll up our sleeves and get started.' },
      { idiom: 'Wear your heart on your sleeve', meaning: 'To show your emotions openly.', example: 'He wears his heart on his sleeve; you always know how he feels.' },
      { idiom: 'If the shoe fits, wear it', meaning: 'If something applies to you, accept it.', example: 'I wasn\'t calling you lazy specifically, but if the shoe fits, wear it.' },
      { idiom: 'Tighten your belt', meaning: 'To spend less money; to economize.', example: 'With the economic downturn, we all need to tighten our belts.' },
      { idiom: 'Below the belt', meaning: 'Unfair or inappropriate.', example: 'That comment about his family was below the belt.' },
      { idiom: 'Dressed to kill', meaning: 'Dressed in fancy or stylish clothes.', example: 'She arrived at the party dressed to kill.' },
      { idiom: 'Put yourself in someone else\'s shoes', meaning: 'To imagine yourself in another person\'s situation.', example: 'Put yourself in his shoes and try to understand his perspective.' },
      { idiom: 'Fill someone\'s shoes', meaning: 'To take over someone\'s position or responsibilities.', example: 'It will be hard to fill her shoes when she retires.' },
      { idiom: 'Hand-me-down', meaning: 'Something that is passed down from one person to another.', example: 'Most of my clothes as a kid were hand-me-downs from my older brother.' },
    ],
  },
];
