export interface AcademicWord {
  word: string;
  partOfSpeech: string;
  definition: string;
  example: string;
  pronunciation: string;
}

export const ACADEMIC_WORDS: AcademicWord[] = [
  { word: 'Abolish', partOfSpeech: 'verb', definition: 'To formally put an end to a system, practice, or institution.', example: 'Many countries have moved to abolish the death penalty.', pronunciation: '/əˈbɒlɪʃ/' },
  { word: 'Abstract', partOfSpeech: 'adjective', definition: 'Existing in thought or as an idea rather than having a physical existence.', example: 'Justice is an abstract concept that varies across cultures.', pronunciation: '/ˈæbstrækt/' },
  { word: 'Accommodate', partOfSpeech: 'verb', definition: 'To provide space or adjust to fit the needs of something or someone.', example: 'The new policy was designed to accommodate students with disabilities.', pronunciation: '/əˈkɒmədeɪt/' },
  { word: 'Accumulate', partOfSpeech: 'verb', definition: 'To gradually gather or collect an increasing amount of something.', example: 'Evidence has accumulated to suggest that the treatment is effective.', pronunciation: '/əˈkjuːmjəleɪt/' },
  { word: 'Acknowledge', partOfSpeech: 'verb', definition: 'To recognize or admit the existence or truth of something.', example: 'The researcher acknowledged the limitations of the study.', pronunciation: '/əkˈnɒlɪdʒ/' },
  { word: 'Acquire', partOfSpeech: 'verb', definition: 'To come to have or obtain something, especially over time.', example: 'Children acquire language naturally through immersion.', pronunciation: '/əˈkwaɪər/' },
  { word: 'Adequate', partOfSpeech: 'adjective', definition: 'Satisfactory or acceptable in quality or quantity.', example: 'The study did not provide adequate evidence to support its conclusions.', pronunciation: '/ˈædɪkwət/' },
  { word: 'Adjacent', partOfSpeech: 'adjective', definition: 'Next to or adjoining something else.', example: 'The two countries are adjacent, sharing a border of over 2,000 kilometres.', pronunciation: '/əˈdʒeɪsənt/' },
  { word: 'Albeit', partOfSpeech: 'conjunction', definition: 'Although; even though.', example: 'The results were positive, albeit inconclusive.', pronunciation: '/ɔːlˈbiːɪt/' },
  { word: 'Allocate', partOfSpeech: 'verb', definition: 'To distribute resources or duties for a particular purpose.', example: 'The government plans to allocate more funding to public health.', pronunciation: '/ˈæləkeɪt/' },
  { word: 'Ambiguous', partOfSpeech: 'adjective', definition: 'Open to more than one interpretation; not clear.', example: 'The law was ambiguous and open to different readings.', pronunciation: '/æmˈbɪɡjuəs/' },
  { word: 'Analogous', partOfSpeech: 'adjective', definition: 'Comparable in certain respects; similar in function.', example: 'The human eye is analogous to a camera in many ways.', pronunciation: '/əˈnæləɡəs/' },
  { word: 'Anticipate', partOfSpeech: 'verb', definition: 'To expect or predict a future event and prepare for it.', example: 'Economists anticipate a rise in inflation over the next quarter.', pronunciation: '/ænˈtɪsɪpeɪt/' },
  { word: 'Apparent', partOfSpeech: 'adjective', definition: 'Clearly visible or understood; obvious.', example: 'It was apparent that the experiment had failed.', pronunciation: '/əˈpærənt/' },
  { word: 'Apprehensive', partOfSpeech: 'adjective', definition: 'Anxious or fearful about a future event.', example: 'Many students feel apprehensive before important exams.', pronunciation: '/ˌæprɪˈhensɪv/' },
  { word: 'Arbitrary', partOfSpeech: 'adjective', definition: 'Based on random choice rather than reason or system.', example: 'The selection process seemed arbitrary and unfair.', pronunciation: '/ˈɑːbɪtrəri/' },
  { word: 'Articulate', partOfSpeech: 'verb', definition: 'To express an idea clearly and effectively.', example: 'She was able to articulate her argument with great precision.', pronunciation: '/ɑːˈtɪkjəleɪt/' },
  { word: 'Assert', partOfSpeech: 'verb', definition: 'To state a fact or belief confidently and forcefully.', example: 'The author asserts that climate change is the defining issue of our time.', pronunciation: '/əˈsɜːt/' },
  { word: 'Assess', partOfSpeech: 'verb', definition: 'To evaluate or estimate the nature, value, or quality of something.', example: 'Teachers must regularly assess student progress.', pronunciation: '/əˈses/' },
  { word: 'Assumption', partOfSpeech: 'noun', definition: 'Something accepted as true without proof.', example: 'The theory rests on several questionable assumptions.', pronunciation: '/əˈsʌmpʃən/' },
  { word: 'Attribute', partOfSpeech: 'verb', definition: 'To regard something as caused by or belonging to something.', example: 'The success of the program was attributed to strong leadership.', pronunciation: '/əˈtrɪbjuːt/' },
  { word: 'Augment', partOfSpeech: 'verb', definition: 'To make something greater by adding to it.', example: 'Technology can augment human capabilities in the workplace.', pronunciation: '/ɔːɡˈment/' },
  { word: 'Coherent', partOfSpeech: 'adjective', definition: 'Logical and consistent; forming a unified whole.', example: 'A coherent argument is essential for persuasive writing.', pronunciation: '/kəʊˈhɪərənt/' },
  { word: 'Comprehensive', partOfSpeech: 'adjective', definition: 'Including or dealing with all or nearly all aspects of something.', example: 'The report provided a comprehensive overview of the issue.', pronunciation: '/ˌkɒmprɪˈhensɪv/' },
  { word: 'Concede', partOfSpeech: 'verb', definition: 'To admit that something is true, especially reluctantly.', example: 'The politician conceded that mistakes had been made.', pronunciation: '/kənˈsiːd/' },
  { word: 'Constitute', partOfSpeech: 'verb', definition: 'To be or make up something.', example: 'Women constitute over half of the university\'s student population.', pronunciation: '/ˈkɒnstɪtjuːt/' },
  { word: 'Contradict', partOfSpeech: 'verb', definition: 'To deny the truth of a statement by saying the opposite.', example: 'The new findings contradict the original hypothesis.', pronunciation: '/ˌkɒntrəˈdɪkt/' },
  { word: 'Controversial', partOfSpeech: 'adjective', definition: 'Giving rise to public disagreement.', example: 'The policy remains highly controversial among experts.', pronunciation: '/ˌkɒntrəˈvɜːʃəl/' },
  { word: 'Conventional', partOfSpeech: 'adjective', definition: 'Based on or following accepted norms or traditions.', example: 'Conventional medicine focuses on treating symptoms rather than causes.', pronunciation: '/kənˈvenʃənəl/' },
  { word: 'Correlate', partOfSpeech: 'verb', definition: 'To have a mutual relationship or connection with something else.', example: 'Higher education levels tend to correlate with higher income.', pronunciation: '/ˈkɒrəleɪt/' },
  { word: 'Criteria', partOfSpeech: 'noun', definition: 'Principles or standards used to judge or evaluate something.', example: 'Applicants must meet strict criteria to be considered for the position.', pronunciation: '/kraɪˈtɪərɪə/' },
  { word: 'Crucial', partOfSpeech: 'adjective', definition: 'Decisive or critical in importance.', example: 'Early intervention is crucial in treating the disease effectively.', pronunciation: '/ˈkruːʃəl/' },
  { word: 'Cumulative', partOfSpeech: 'adjective', definition: 'Increasing or growing by successive additions.', example: 'The cumulative effect of pollution on the environment is severe.', pronunciation: '/ˈkjuːmjələtɪv/' },
  { word: 'Deduce', partOfSpeech: 'verb', definition: 'To arrive at a conclusion by logical reasoning.', example: 'From the data, we can deduce that demand is falling.', pronunciation: '/dɪˈdjuːs/' },
  { word: 'Deficit', partOfSpeech: 'noun', definition: 'The amount by which something falls short; a shortfall.', example: 'The country faces a significant budget deficit this year.', pronunciation: '/ˈdefɪsɪt/' },
  { word: 'Demonstrate', partOfSpeech: 'verb', definition: 'To show or prove something clearly by giving evidence.', example: 'The experiment clearly demonstrated the validity of the theory.', pronunciation: '/ˈdemənstreɪt/' },
  { word: 'Diminish', partOfSpeech: 'verb', definition: 'To make or become less in size, importance, or intensity.', example: 'The discovery did not diminish the significance of earlier research.', pronunciation: '/dɪˈmɪnɪʃ/' },
  { word: 'Diverse', partOfSpeech: 'adjective', definition: 'Showing a great deal of variety; very different.', example: 'The city has a diverse population from many cultural backgrounds.', pronunciation: '/daɪˈvɜːs/' },
  { word: 'Dominant', partOfSpeech: 'adjective', definition: 'Having power and influence over others; most prominent.', example: 'English has become the dominant language of global business.', pronunciation: '/ˈdɒmɪnənt/' },
  { word: 'Elaborate', partOfSpeech: 'verb', definition: 'To develop or present in detail; to add more information.', example: 'Could you elaborate on the key points of your proposal?', pronunciation: '/ɪˈlæbəreɪt/' },
  { word: 'Emerging', partOfSpeech: 'adjective', definition: 'Becoming prominent or well-known for the first time.', example: 'Artificial intelligence is an emerging field with vast potential.', pronunciation: '/ɪˈmɜːdʒɪŋ/' },
  { word: 'Empirical', partOfSpeech: 'adjective', definition: 'Based on observation or experience rather than theory.', example: 'Empirical evidence is essential for scientific research.', pronunciation: '/ɪmˈpɪrɪkəl/' },
  { word: 'Enhance', partOfSpeech: 'verb', definition: 'To intensify, increase, or further improve the quality of something.', example: 'Regular reading can significantly enhance your vocabulary.', pronunciation: '/ɪnˈhɑːns/' },
  { word: 'Eradicate', partOfSpeech: 'verb', definition: 'To destroy or remove completely.', example: 'Global efforts to eradicate polio have been largely successful.', pronunciation: '/ɪˈrædɪkeɪt/' },
  { word: 'Ethical', partOfSpeech: 'adjective', definition: 'Relating to moral principles; morally right.', example: 'Researchers must follow strict ethical guidelines when working with human subjects.', pronunciation: '/ˈeθɪkəl/' },
  { word: 'Evaluate', partOfSpeech: 'verb', definition: 'To form an opinion about the value or quality of something.', example: 'Students are required to evaluate the reliability of their sources.', pronunciation: '/ɪˈvæljueɪt/' },
  { word: 'Evident', partOfSpeech: 'adjective', definition: 'Clearly seen or understood; obvious.', example: 'The improvement in students\' scores was evident after the new program.', pronunciation: '/ˈevɪdənt/' },
  { word: 'Evolve', partOfSpeech: 'verb', definition: 'To develop gradually over time.', example: 'Language continues to evolve as new words enter common use.', pronunciation: '/ɪˈvɒlv/' },
  { word: 'Explicit', partOfSpeech: 'adjective', definition: 'Stated clearly and in detail, leaving no room for confusion.', example: 'The contract included explicit terms regarding payment.', pronunciation: '/ɪkˈsplɪsɪt/' },
  { word: 'Fluctuate', partOfSpeech: 'verb', definition: 'To rise and fall irregularly in number or amount.', example: 'Currency values fluctuate according to market conditions.', pronunciation: '/ˈflʌktʃueɪt/' },
  { word: 'Formulate', partOfSpeech: 'verb', definition: 'To create or devise a plan, policy, or method systematically.', example: 'Scientists formulate hypotheses before conducting experiments.', pronunciation: '/ˈfɔːmjəleɪt/' },
  { word: 'Fundamental', partOfSpeech: 'adjective', definition: 'Of central importance; forming a necessary base.', example: 'Access to clean water is a fundamental human right.', pronunciation: '/ˌfʌndəˈmentəl/' },
  { word: 'Generate', partOfSpeech: 'verb', definition: 'To produce or create something.', example: 'Renewable energy sources generate electricity without carbon emissions.', pronunciation: '/ˈdʒenəreɪt/' },
  { word: 'Hypothesis', partOfSpeech: 'noun', definition: 'A proposed explanation made on limited evidence as a starting point for investigation.', example: 'The researcher developed a hypothesis about the causes of the disease.', pronunciation: '/haɪˈpɒθəsɪs/' },
  { word: 'Illustrate', partOfSpeech: 'verb', definition: 'To explain or make something clear by using examples or comparisons.', example: 'The graph illustrates the rise in global temperatures over the past century.', pronunciation: '/ˈɪləstreɪt/' },
  { word: 'Implicit', partOfSpeech: 'adjective', definition: 'Implied but not directly expressed.', example: 'There was an implicit agreement that no one would speak about the matter.', pronunciation: '/ɪmˈplɪsɪt/' },
  { word: 'Incentive', partOfSpeech: 'noun', definition: 'Something that motivates or encourages someone to do something.', example: 'Tax reductions serve as an incentive for businesses to invest locally.', pronunciation: '/ɪnˈsentɪv/' },
  { word: 'Inevitable', partOfSpeech: 'adjective', definition: 'Certain to happen; unable to be avoided.', example: 'Globalisation made cultural exchange inevitable.', pronunciation: '/ɪnˈevɪtəbl/' },
  { word: 'Infer', partOfSpeech: 'verb', definition: 'To conclude from evidence and reasoning.', example: 'From the data, we can infer that the trend will continue.', pronunciation: '/ɪnˈfɜː/' },
  { word: 'Innovative', partOfSpeech: 'adjective', definition: 'Introducing new ideas; original and creative.', example: 'The company is known for its innovative approach to product design.', pronunciation: '/ˈɪnəveɪtɪv/' },
  { word: 'Integral', partOfSpeech: 'adjective', definition: 'Necessary to make a whole complete; essential.', example: 'Critical thinking is integral to academic success.', pronunciation: '/ˈɪntɪɡrəl/' },
  { word: 'Interpret', partOfSpeech: 'verb', definition: 'To explain the meaning of something.', example: 'Results can be interpreted in different ways depending on the framework used.', pronunciation: '/ɪnˈtɜːprɪt/' },
  { word: 'Justify', partOfSpeech: 'verb', definition: 'To show or prove to be right or reasonable.', example: 'You must justify your argument with evidence from reliable sources.', pronunciation: '/ˈdʒʌstɪfaɪ/' },
  { word: 'Liable', partOfSpeech: 'adjective', definition: 'Responsible by law; likely to do or suffer something.', example: 'Companies are liable for the environmental damage they cause.', pronunciation: '/ˈlaɪəbl/' },
  { word: 'Legitimate', partOfSpeech: 'adjective', definition: 'Conforming to the law or rules; justifiable.', example: 'The workers had legitimate concerns about their working conditions.', pronunciation: '/lɪˈdʒɪtɪmət/' },
  { word: 'Minimize', partOfSpeech: 'verb', definition: 'To reduce something to the smallest possible amount.', example: 'The company took steps to minimize its environmental impact.', pronunciation: '/ˈmɪnɪmaɪz/' },
  { word: 'Mitigate', partOfSpeech: 'verb', definition: 'To make something less severe or less serious.', example: 'Planting trees can help mitigate the effects of climate change.', pronunciation: '/ˈmɪtɪɡeɪt/' },
  { word: 'Notion', partOfSpeech: 'noun', definition: 'A concept or belief about something.', example: 'The notion that success depends solely on intelligence is outdated.', pronunciation: '/ˈnəʊʃən/' },
  { word: 'Objective', partOfSpeech: 'adjective', definition: 'Not influenced by personal feelings; considering only facts.', example: 'A good academic essay should present an objective analysis of the topic.', pronunciation: '/əbˈdʒektɪv/' },
  { word: 'Obstacle', partOfSpeech: 'noun', definition: 'A thing that blocks or hinders progress.', example: 'Lack of funding remains the biggest obstacle to research.', pronunciation: '/ˈɒbstəkəl/' },
  { word: 'Obtain', partOfSpeech: 'verb', definition: 'To get, acquire, or secure something.', example: 'You must obtain permission before using copyrighted material.', pronunciation: '/əbˈteɪn/' },
  { word: 'Paradigm', partOfSpeech: 'noun', definition: 'A typical example or pattern; a model or framework.', example: 'The discovery led to a paradigm shift in scientific thinking.', pronunciation: '/ˈpærədaɪm/' },
  { word: 'Perceive', partOfSpeech: 'verb', definition: 'To become aware of or understand something.', example: 'Many people perceive social media as a threat to privacy.', pronunciation: '/pəˈsiːv/' },
  { word: 'Persist', partOfSpeech: 'verb', definition: 'To continue firmly despite obstacles or opposition.', example: 'Inequality tends to persist without targeted government intervention.', pronunciation: '/pəˈsɪst/' },
  { word: 'Phenomenon', partOfSpeech: 'noun', definition: 'A fact or situation that is observed to exist, especially one whose cause is in question.', example: 'Urban migration is a global phenomenon driven by economic factors.', pronunciation: '/fɪˈnɒmɪnən/' },
  { word: 'Pragmatic', partOfSpeech: 'adjective', definition: 'Dealing with things practically rather than theoretically.', example: 'The manager took a pragmatic approach to solving the budget crisis.', pronunciation: '/præɡˈmætɪk/' },
  { word: 'Premise', partOfSpeech: 'noun', definition: 'A statement assumed to be true as the basis for an argument.', example: 'The argument rests on the premise that education reduces poverty.', pronunciation: '/ˈpremɪs/' },
  { word: 'Prevalent', partOfSpeech: 'adjective', definition: 'Widespread in a particular area at a particular time.', example: 'Obesity is increasingly prevalent in developed countries.', pronunciation: '/ˈprevələnt/' },
  { word: 'Principle', partOfSpeech: 'noun', definition: 'A fundamental truth or proposition that serves as the foundation for a system.', example: 'The principle of equality underpins democratic governance.', pronunciation: '/ˈprɪnsɪpəl/' },
  { word: 'Profound', partOfSpeech: 'adjective', definition: 'Having great depth or intensity; very great.', example: 'The industrial revolution had a profound effect on society.', pronunciation: '/prəˈfaʊnd/' },
  { word: 'Promote', partOfSpeech: 'verb', definition: 'To support or actively encourage a cause, venture, or aim.', example: 'The campaign aims to promote healthy lifestyle choices.', pronunciation: '/prəˈməʊt/' },
  { word: 'Proportion', partOfSpeech: 'noun', definition: 'A part, share, or number considered in comparison with a whole.', example: 'A large proportion of the population lives in urban areas.', pronunciation: '/prəˈpɔːʃən/' },
  { word: 'Rationale', partOfSpeech: 'noun', definition: 'A set of reasons or logical basis for a course of action.', example: 'The report explained the rationale behind the new policy.', pronunciation: '/ˌræʃəˈnɑːl/' },
  { word: 'Reinforce', partOfSpeech: 'verb', definition: 'To strengthen or support, especially with additional evidence.', example: 'These findings reinforce the importance of early childhood education.', pronunciation: '/ˌriːɪnˈfɔːs/' },
  { word: 'Relevant', partOfSpeech: 'adjective', definition: 'Closely connected or appropriate to the matter in hand.', example: 'Only relevant evidence should be included in an academic argument.', pronunciation: '/ˈreləvənt/' },
  { word: 'Reluctant', partOfSpeech: 'adjective', definition: 'Unwilling and hesitant.', example: 'Many people are reluctant to change long-established habits.', pronunciation: '/rɪˈlʌktənt/' },
  { word: 'Repercussion', partOfSpeech: 'noun', definition: 'An unintended consequence occurring later as a result of an event.', example: 'The financial crisis had serious repercussions for global trade.', pronunciation: '/ˌriːpəˈkʌʃən/' },
  { word: 'Resolve', partOfSpeech: 'verb', definition: 'To find a solution to a problem or dispute.', example: 'Negotiations were held to resolve the conflict peacefully.', pronunciation: '/rɪˈzɒlv/' },
  { word: 'Restrict', partOfSpeech: 'verb', definition: 'To put a limit on; keep under control.', example: 'New laws restrict the use of single-use plastics.', pronunciation: '/rɪˈstrɪkt/' },
  { word: 'Retain', partOfSpeech: 'verb', definition: 'To continue to have something; keep possession of.', example: 'It is important to retain key staff during times of transition.', pronunciation: '/rɪˈteɪn/' },
  { word: 'Significant', partOfSpeech: 'adjective', definition: 'Important, notable, or large enough to have an effect.', example: 'There was a significant increase in unemployment last year.', pronunciation: '/sɪɡˈnɪfɪkənt/' },
  { word: 'Simultaneously', partOfSpeech: 'adverb', definition: 'At the same time.', example: 'The two processes occur simultaneously in the cell.', pronunciation: '/ˌsɪməlˈteɪniəsli/' },
  { word: 'Sophisticated', partOfSpeech: 'adjective', definition: 'Developed to a high degree of complexity or refinement.', example: 'Modern technology provides increasingly sophisticated tools for learning.', pronunciation: '/səˈfɪstɪkeɪtɪd/' },
  { word: 'Subjective', partOfSpeech: 'adjective', definition: 'Based on personal feelings or opinions rather than facts.', example: 'Art appreciation is often considered a subjective experience.', pronunciation: '/səbˈdʒektɪv/' },
  { word: 'Substantial', partOfSpeech: 'adjective', definition: 'Of considerable size, value, or importance.', example: 'The project required a substantial investment of time and resources.', pronunciation: '/səbˈstænʃəl/' },
  { word: 'Sufficient', partOfSpeech: 'adjective', definition: 'Enough; adequate for the purpose.', example: 'There is not sufficient evidence to draw a definitive conclusion.', pronunciation: '/səˈfɪʃənt/' },
  { word: 'Sustain', partOfSpeech: 'verb', definition: 'To maintain or support over a long period.', example: 'Sustainable agriculture helps sustain food supplies for future generations.', pronunciation: '/səˈsteɪn/' },
  { word: 'Tendency', partOfSpeech: 'noun', definition: 'An inclination towards a particular way of behaving.', example: 'There is a tendency to overlook the social causes of crime.', pronunciation: '/ˈtendənsi/' },
  { word: 'Theoretical', partOfSpeech: 'adjective', definition: 'Concerned with theory rather than practice.', example: 'The paper presents a theoretical framework for understanding behaviour.', pronunciation: '/ˌθɪəˈretɪkəl/' },
  { word: 'Transform', partOfSpeech: 'verb', definition: 'To make a thorough or dramatic change in form, appearance, or character.', example: 'Digital technology has transformed the way people communicate.', pronunciation: '/trænsˈfɔːm/' },
  { word: 'Undermine', partOfSpeech: 'verb', definition: 'To weaken or damage something, especially gradually.', example: 'Corruption can undermine trust in public institutions.', pronunciation: '/ˌʌndəˈmaɪn/' },
  { word: 'Universal', partOfSpeech: 'adjective', definition: 'Applicable to all cases; relating to all people.', example: 'Education is widely considered to be a universal right.', pronunciation: '/ˌjuːnɪˈvɜːsəl/' },
  { word: 'Validate', partOfSpeech: 'verb', definition: 'To demonstrate or confirm the truth or validity of something.', example: 'Further research is needed to validate these preliminary findings.', pronunciation: '/ˈvælɪdeɪt/' },
  { word: 'Variable', partOfSpeech: 'noun', definition: 'An element that can change or be changed in an experiment.', example: 'Temperature was controlled as a variable in the experiment.', pronunciation: '/ˈveərɪəbl/' },
  { word: 'Viable', partOfSpeech: 'adjective', definition: 'Capable of working successfully; feasible.', example: 'Solar power is a viable alternative to fossil fuels.', pronunciation: '/ˈvaɪəbl/' },
  { word: 'Volatility', partOfSpeech: 'noun', definition: 'A tendency to change rapidly and unpredictably.', example: 'Market volatility makes long-term investment planning difficult.', pronunciation: '/ˌvɒləˈtɪlɪti/' },
  { word: 'Widespread', partOfSpeech: 'adjective', definition: 'Distributed or occurring over a wide area or among many people.', example: 'Misinformation has become widespread due to social media.', pronunciation: '/ˈwaɪdspred/' },
  { word: 'Yield', partOfSpeech: 'verb', definition: 'To produce or provide a natural, agricultural, or industrial product.', example: 'The experiment yielded unexpected but significant results.', pronunciation: '/jiːld/' },
  { word: 'Ambivalent', partOfSpeech: 'adjective', definition: 'Having mixed feelings or contradictory ideas about something.', example: 'Many voters felt ambivalent about the proposed reforms.', pronunciation: '/æmˈbɪvələnt/' },
  { word: 'Concise', partOfSpeech: 'adjective', definition: 'Giving a lot of information clearly in few words.', example: 'A concise summary is more effective than a lengthy explanation.', pronunciation: '/kənˈsaɪs/' },
  { word: 'Contentious', partOfSpeech: 'adjective', definition: 'Causing or likely to cause argument.', example: 'Immigration remains a contentious issue in many democracies.', pronunciation: '/kənˈtenʃəs/' },
  { word: 'Deplete', partOfSpeech: 'verb', definition: 'To use up the supply or resources of something.', example: 'Overfishing has depleted fish stocks in many of the world\'s oceans.', pronunciation: '/dɪˈpliːt/' },
  { word: 'Detrimental', partOfSpeech: 'adjective', definition: 'Causing harm or damage.', example: 'Excessive screen time can be detrimental to children\'s development.', pronunciation: '/ˌdetrɪˈmentəl/' },
  { word: 'Disparity', partOfSpeech: 'noun', definition: 'A great difference between things; inequality.', example: 'The disparity in income between rich and poor has widened.', pronunciation: '/dɪˈspærɪti/' },
  { word: 'Discourse', partOfSpeech: 'noun', definition: 'Written or spoken communication or debate.', example: 'Academic discourse requires precision and clarity of expression.', pronunciation: '/ˈdɪskɔːs/' },
  { word: 'Encompass', partOfSpeech: 'verb', definition: 'To include a wide range of things.', example: 'The course encompasses a broad range of topics in linguistics.', pronunciation: '/ɪnˈkʌmpəs/' },
  { word: 'Equitable', partOfSpeech: 'adjective', definition: 'Fair and impartial; treating everyone equally.', example: 'The goal is to create a more equitable distribution of wealth.', pronunciation: '/ˈekwɪtəbl/' },
  { word: 'Facilitate', partOfSpeech: 'verb', definition: 'To make an action or process easier.', example: 'Technology can facilitate communication across long distances.', pronunciation: '/fəˈsɪlɪteɪt/' },
  { word: 'Feasible', partOfSpeech: 'adjective', definition: 'Possible to do easily or conveniently.', example: 'The committee assessed whether the plan was economically feasible.', pronunciation: '/ˈfiːzɪbəl/' },
  { word: 'Fluctuation', partOfSpeech: 'noun', definition: 'An irregular rising and falling in number or amount.', example: 'Fluctuations in oil prices affect the global economy.', pronunciation: '/ˌflʌktʃuˈeɪʃən/' },
  { word: 'Hierarchy', partOfSpeech: 'noun', definition: 'A system in which members are ranked one above another.', example: 'Most large organisations operate within a clear hierarchy.', pronunciation: '/ˈhaɪərɑːki/' },
  { word: 'Implication', partOfSpeech: 'noun', definition: 'A conclusion that can be drawn from something, though not directly stated.', example: 'The findings have important implications for healthcare policy.', pronunciation: '/ˌɪmplɪˈkeɪʃən/' },
  { word: 'Inconsistent', partOfSpeech: 'adjective', definition: 'Not staying the same; contradictory or irregular.', example: 'The data from the two studies were inconsistent with each other.', pronunciation: '/ˌɪnkənˈsɪstənt/' },
  { word: 'Inherent', partOfSpeech: 'adjective', definition: 'Existing naturally as a part of something.', example: 'There are inherent risks in any form of investment.', pronunciation: '/ɪnˈhɪərənt/' },
  { word: 'Marginalise', partOfSpeech: 'verb', definition: 'To treat as unimportant or to exclude from the centre of society.', example: 'Certain groups are systematically marginalised by the education system.', pronunciation: '/ˈmɑːdʒɪnəlaɪz/' },
  { word: 'Methodology', partOfSpeech: 'noun', definition: 'A system of methods used in a particular field.', example: 'The study\'s methodology was transparent and well-documented.', pronunciation: '/ˌmeθəˈdɒlədʒi/' },
  { word: 'Nuance', partOfSpeech: 'noun', definition: 'A subtle difference in meaning, expression, or sound.', example: 'Good writers are sensitive to the nuance of language.', pronunciation: '/ˈnjuːɑːns/' },
];

/** Returns a random word each time the page is loaded. */
export function getTodaysWord(): AcademicWord {
  const index = Math.floor(Math.random() * ACADEMIC_WORDS.length);
  return ACADEMIC_WORDS[index];
}
