// One-off code-mod: extract metadata from grammarTopics.tsx and blogPosts.tsx
// into small standalone TS files so navigation/listing components don't pull
// the entire content payload (~1.3MB blog + 280KB grammar).
//
// Run with: node scripts/extract-meta.cjs
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');

// ---- 1. Grammar topics meta -------------------------------------------------
const gtSrc = fs.readFileSync(path.join(root, 'src/constants/grammarTopics.tsx'), 'utf8');
const gtRe = /id:\s*'([^']+)',\s*title:\s*'([^']+)',\s*category:\s*'([^']+)'/g;
const gtItems = [];
let m;
while ((m = gtRe.exec(gtSrc)) !== null) {
  gtItems.push({ id: m[1], title: m[2], category: m[3] });
}
console.log(`Found ${gtItems.length} grammar topics`);

const gtMeta =
  `// AUTO-GENERATED by scripts/extract-meta.cjs — do not edit by hand.\n` +
  `// Re-run that script after editing grammarTopics.tsx.\n` +
  `export interface GrammarTopicMeta {\n` +
  `  id: string;\n` +
  `  title: string;\n` +
  `  category: string;\n` +
  `}\n\n` +
  `export const GRAMMAR_TOPICS_META: GrammarTopicMeta[] = ${JSON.stringify(gtItems, null, 2)};\n`;
fs.writeFileSync(path.join(root, 'src/constants/grammarTopicsMeta.ts'), gtMeta, 'utf8');
console.log('Wrote src/constants/grammarTopicsMeta.ts');

// ---- 2. Blog posts meta -----------------------------------------------------
const bpSrc = fs.readFileSync(path.join(root, 'src/constants/blogPosts.tsx'), 'utf8');

// Match each blog post object's metadata block. Posts begin with `slug:` and
// have predictable string fields followed by either `image:`, `imageAlt:`, or
// `schemaMarkup`/`content:` next. We capture optional image fields too.
const bpRe = /slug:\s*'([^']+)',\s*\n\s*title:\s*'((?:[^'\\]|\\.)*)',\s*\n\s*author:\s*'((?:[^'\\]|\\.)*)',\s*\n\s*date:\s*'((?:[^'\\]|\\.)*)',\s*\n\s*summary:\s*'((?:[^'\\]|\\.)*)',\s*\n\s*category:\s*'((?:[^'\\]|\\.)*)'(?:,\s*\n\s*image:\s*'((?:[^'\\]|\\.)*)')?(?:,\s*\n\s*imageAlt:\s*'((?:[^'\\]|\\.)*)')?/g;
const bpRawItems = [];
let bm;
while ((bm = bpRe.exec(bpSrc)) !== null) {
  bpRawItems.push({
    matchIndex: bm.index,
    slug: bm[1],
    title: bm[2].replace(/\\'/g, "'"),
    author: bm[3].replace(/\\'/g, "'"),
    date: bm[4].replace(/\\'/g, "'"),
    summary: bm[5].replace(/\\'/g, "'"),
    category: bm[6].replace(/\\'/g, "'"),
    image: bm[7] ? bm[7].replace(/\\'/g, "'") : undefined,
    imageAlt: bm[8] ? bm[8].replace(/\\'/g, "'") : undefined,
  });
}
console.log(`Found ${bpRawItems.length} blog posts`);

// Estimate reading time per post by isolating its content block and counting
// human-readable words. We slice from this post's slug position to the next
// post's slug position (or EOF), then strip JSX/attribute/code noise.
const WORDS_PER_MINUTE = 220;

function countContentWords(block) {
  let text = block;
  // 1. Remove import/jsx attribute values entirely (className="...", to="...", etc.)
  //    Handles string and brace-expression values.
  text = text.replace(/\s+[a-zA-Z][\w-]*=("(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'|\{(?:[^{}]|\{[^}]*\})*\})/g, ' ');
  // 2. Remove JSX tags (opening, closing, self-closing, fragments)
  text = text.replace(/<\/?[A-Za-z][^>]*\/?>/g, ' ');
  text = text.replace(/<\/?>/g, ' ');
  // 3. Drop schemaMarkup blocks (JSON-LD inside metadata — not part of read time)
  text = text.replace(/schemaMarkup:\s*\{[\s\S]*?\n\s{4,6}\},?/g, ' ');
  // 4. Count word-like tokens of 2+ letters
  const tokens = text.match(/\b[a-zA-Z][a-zA-Z']{1,}\b/g) || [];
  return tokens.length;
}

const bpItems = bpRawItems.map((raw, i) => {
  const start = raw.matchIndex;
  const end = i + 1 < bpRawItems.length ? bpRawItems[i + 1].matchIndex : bpSrc.length;
  const block = bpSrc.slice(start, end);
  // Take only the content section, after `content:` if present
  const contentIdx = block.indexOf('content:');
  const contentBlock = contentIdx >= 0 ? block.slice(contentIdx) : block;
  const words = countContentWords(contentBlock);
  const readMinutes = Math.max(2, Math.round(words / WORDS_PER_MINUTE));
  return {
    slug: raw.slug,
    title: raw.title,
    author: raw.author,
    date: raw.date,
    summary: raw.summary,
    category: raw.category,
    image: raw.image,
    imageAlt: raw.imageAlt,
    readMinutes,
  };
});

const bpMeta =
  `// AUTO-GENERATED by scripts/extract-meta.cjs — do not edit by hand.\n` +
  `// Re-run that script after editing blogPosts.tsx.\n` +
  `export interface BlogPostMeta {\n` +
  `  slug: string;\n` +
  `  title: string;\n` +
  `  author: string;\n` +
  `  date: string;\n` +
  `  summary: string;\n` +
  `  category: string;\n` +
  `  image?: string;\n` +
  `  imageAlt?: string;\n` +
  `  readMinutes: number;\n` +
  `}\n\n` +
  `export const BLOG_POSTS_META: BlogPostMeta[] = ${JSON.stringify(bpItems, null, 2)};\n`;
fs.writeFileSync(path.join(root, 'src/constants/blogPostsMeta.ts'), bpMeta, 'utf8');
console.log('Wrote src/constants/blogPostsMeta.ts');
